(source "elpa" "https://tromey.com/elpa/")
;; (source "melpa" "https://melpa.milkbox.net/packages/")
(source "melpa" "http://melpa.org/packages/")

(source gnu)
(source marmalade)

(depends-on "ag")
(depends-on "alchemist")
(depends-on "async")
(depends-on "bind-key")
(depends-on "beacon")
(depends-on "cask")
(depends-on "coffee-mode")
(depends-on "color-theme")
(depends-on "company")
(depends-on "concurrent")
(depends-on "ctable")
(depends-on "dash")
(depends-on "dash-functional")
(depends-on "deferred")
(depends-on "diminish")
(depends-on "duplicate-thing")
(depends-on "elixir-mode")
(depends-on "epc")
(depends-on "epl")

(depends-on "evil")
(depends-on "evil-escape")
(depends-on "evil-indent-plus")
(depends-on "evil-leader")
(depends-on "evil-matchit")
(depends-on "evil-commentary")
(depends-on "evil-numbers")
(depends-on "evil-surround")
(depends-on "evil-visualstar")
(depends-on "evil-rails")
(depends-on "evil-quickscope")
(depends-on "evil-magit")
(depends-on "evil-exchange")
(depends-on "evil-lion")
(depends-on "evil-textobj-anyblock")

(depends-on "exec-path-from-shell")
(depends-on "f")
(depends-on "fill-column-indicator")
(depends-on "flx")
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "full-ack")
(depends-on "ggtags")
(depends-on "gh")
(depends-on "git-commit")
(depends-on "git-gutter")
(depends-on "github-browse-file")
(depends-on "goto-chg")
(depends-on "haml-mode")
(depends-on "highline")
(depends-on "ido-completing-read+")
(depends-on "ido-vertical-mode")
(depends-on "inf-ruby")
(depends-on "inflections")
(depends-on "key-chord")
(depends-on "logito")
(depends-on "magit")
(depends-on "magit-popup")
(depends-on "markdown-mode")
(depends-on "markdown-mode+")
(depends-on "minitest")
(depends-on "mmm-mode")
(depends-on "neotree")
(depends-on "package-build")
(depends-on "pbcopy")
(depends-on "pcache")
(depends-on "pkg-info")
(depends-on "popup")
(depends-on "popwin")
(depends-on "powerline")
(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "rake")
(depends-on "rbenv")
(depends-on "robe")
(depends-on "rspec-mode")
(depends-on "rubocop")
(depends-on "ruby-hash-syntax")
(depends-on "ruby-tools")
(depends-on "rvm")
(depends-on "enh-ruby-mode")
(depends-on "s")
(depends-on "sass-mode")
(depends-on "shut-up")
(depends-on "smart-newline")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "smooth-scrolling")
(depends-on "undo-tree")
(depends-on "use-package")
(depends-on "visual-fill-column")
(depends-on "web-beautify")
(depends-on "web-mode")
(depends-on "with-editor")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "slim-mode")
(depends-on "swiper")
(depends-on "fullframe")
(depends-on "json-mode")
(depends-on "adoc-mode")
(depends-on "dumb-jump")
(depends-on "exato")
(depends-on "aggressive-indent")
(depends-on "prettier-js")
(depends-on "crystal-mode")
(depends-on "pug-mode")
(depends-on "csv-mode")

(depends-on "ivy")
(depends-on "ivy-rich")
(depends-on "flyspell-correct-ivy")
(depends-on "savehist")
(depends-on "org-bullets")

(depends-on "hydra")
(depends-on "counsel")
(depends-on "counsel-projectile")
(depends-on "vue-mode")
(depends-on "vue-html-mode")

;; Experimental
(depends-on "fireplace")
(depends-on "editorconfig")
(depends-on "browse-at-remote")
(depends-on "beacon")

(depends-on "dockerfile-mode")
(depends-on "docker-compose-mode")

(depends-on "forge")
(depends-on "noflet")

(depends-on "reveal-in-folder")
(depends-on "lorem-ipsum")
(depends-on "doom-modeline")

(depends-on "vterm-toggle")
(depends-on "eglot")

(depends-on "selectrum")
