;;; neptune-theme.el --- Neptune theme for GNU Emacs 24 (deftheme)

(deftheme neptune "The neptune color theme")

(let ((class '((class color) (min-colors 89)))
      (neptune-fg       "#FFFFFF")
      (neptune-bg       "#1d1f21")
      (neptune-blue     "#96CBFE")
      (neptune-green-0  "#99CC99")
      (neptune-green-2  "#a8ff60")
      (neptune-grey-0   "#888888")
      (neptune-grey-1   "#7f7f7f")
      (neptune-grey-2   "#151515")
      (neptune-grey-3   "#1c1c1c")
      (neptune-grey-4   "#212325")
      (neptune-grey-5   "#444444")
      (neptune-orange   "#ffd080")
      (neptune-purple   "#c3c2ef")
      (neptune-purple-1 "#474e90")
      (neptune-purple-2 "#cd00cd")
      (neptune-red-0    "#e36049")
      (neptune-red-1    "#dd0093")
      (neptune-red-2    "#de5577")
      (neptune-red-3    "#ff73fd")
      (neptune-yellow   "#feffd2")
      )

      (custom-theme-set-faces
       'neptune

       ;;----------------------------------------------------------------------------
       ;; Base level colors
       ;;----------------------------------------------------------------------------

       `(default ((,class (:foreground ,neptune-fg :background ,neptune-bg))))
       `(header-line ((,class (:foreground ,neptune-fg))))
       `(highlight ((,class (:background ,neptune-grey-4))))
       `(hl-line ((,class (:background ,neptune-grey-4))))
       `(fringe ((,class (:foreground ,neptune-fg :background ,neptune-bg))))

       `(font-lock-comment-face ((,class (:slant italic :foreground ,neptune-grey-1))))
       `(font-lock-preprocessor-face ((,class (:foreground ,neptune-fg))))

       `(font-lock-builtin-face ((,class (:foreground ,neptune-purple))))
       `(font-lock-constant-face ((,class (:foreground , neptune-purple))))

       `(font-lock-doc-face ((,class (:foreground ,neptune-green-0))))
       `(font-lock-function-name-face ((,class (:foreground ,neptune-orange))))
       `(font-lock-keyword-face ((,class (:foreground ,neptune-blue))))
       `(font-lock-string-face ((,class (:foreground ,neptune-green-0))))
       `(font-lock-type-face ((,class (:foreground ,neptune-orange))))
       `(font-lock-variable-name-face ((,class (:foreground ,neptune-purple))))
       `(font-lock-warning-face ((,class (:foreground ,neptune-red-1))))
       `(font-lock-regexp-grouping-construct ((t (:foreground ,neptune-yellow :bold t))))
       `(font-lock-regexp-grouping-backslash ((t (:foreground ,neptune-red-0 :bold t))))

       ;;----------------------------------------------------------------------------
       ;; Dired mode
       ;;----------------------------------------------------------------------------

       `(diredp-date-time ((,class (:foreground ,neptune-fg))))
       `(diredp-deletion ((,class (:foreground ,neptune-red-0 :background ,neptune-bg))))
       `(diredp-dir-heading ((,class (:foreground ,neptune-yellow :background ,neptune-bg))))
       `(diredp-dir-name ((,class (:foreground ,neptune-green-2 :background ,neptune-bg))))
       `(diredp-dir-priv ((,class (:foreground ,neptune-green-2 :background ,neptune-bg))))
       `(diredp-exec-priv ((,class (:foreground ,neptune-fg :background ,neptune-bg))))
       `(diredp-file-name ((,class (:foreground ,neptune-fg))))
       `(diredp-file-suffix ((,class (:foreground ,neptune-fg))))
       `(diredp-link-priv ((,class (:foreground ,neptune-fg))))
       `(diredp-number ((,class (:foreground ,neptune-fg))))
       `(diredp-no-priv ((,class (:foreground ,neptune-fg :background ,neptune-bg))))
       `(diredp-rare-priv ((,class (:foreground ,neptune-red-0 :background ,neptune-bg))))
       `(diredp-read-priv ((,class (:foreground ,neptune-fg :background ,neptune-bg))))
       `(diredp-symlink ((,class (:foreground ,neptune-red-3))))
       `(diredp-write-priv ((,class (:foreground ,neptune-fg :background ,neptune-bg))))

       ;;----------------------------------------------------------------------------
       ;; Helm mode
       ;;----------------------------------------------------------------------------

       `(helm-buffer-file ((,class (:foreground ,neptune-fg))))
       `(helm-buffer-process ((,class (:foreground ,neptune-yellow))))
       `(helm-buffer-size ((,class (:foreground ,neptune-fg))))
       `(helm-candidate-number ((,class (:foreground ,neptune-fg :background ,neptune-bg))))
       `(helm-ff-directory ((,class (:foreground ,neptune-green-2))))
       `(helm-ff-dotted-directory ((,class (:foreground ,neptune-green-2 :background ,neptune-bg))))
       `(helm-ff-dotted-symlink-directory ((,class (:foreground ,neptune-green-2 :background ,neptune-bg))))
       `(helm-ff-executable ((,class (:foreground ,neptune-red-0))))
       `(helm-ff-file ((,class (:foreground ,neptune-fg))))
       `(helm-ff-symlink ((,class (:foreground ,neptune-purple-2))))
       `(helm-grep-lineno ((,class (:foreground ,neptune-fg))))
       `(helm-match ((,class (:foreground ,neptune-red-0 :background ,neptune-bg))))
       `(helm-moccur-buffer ((,class (:foreground ,neptune-yellow))))
       `(helm-selection ((,class (:background ,neptune-purple-1))))
       `(helm-source-header ((,class (:foreground ,neptune-yellow :background ,neptune-grey-3))))
       `(helm-swoop-target-line-face ((,class (:foreground ,neptune-fg :background ,neptune-grey-0))))
       `(helm-swoop-target-word-face ((,class (:foreground ,neptune-red-0))))


       `(alchemist-test--failed-face ((,class (:foreground ,neptune-red-0))))
       `(alchemist-test--success-face ((,class (:foreground ,neptune-green-0))))
       `(avy-lead-face ((,class (:foreground ,neptune-fg :background ,neptune-red-0))))
       `(avy-lead-face-0 ((,class (:foreground ,neptune-fg :background ,neptune-green-0))))
       `(bm-face ((,class (:background ,neptune-grey-4))))
       `(company-preview-common ((,class (:foreground nil :background ,neptune-purple-1))))
       `(company-scrollbar-bg ((,class (:background ,neptune-grey-2))))
       `(company-scrollbar-fg ((,class (:background ,neptune-grey-0))))
       `(company-tooltip ((,class (:foreground ,neptune-fg :background ,neptune-grey-2))))
       `(company-tooltip-common ((,class (:foreground ,neptune-red-0 :background ,neptune-grey-2))))
       `(company-tooltip-common-selection ((,class (:foreground ,neptune-red-0 :background ,neptune-purple-1))))
       `(company-tooltip-selection ((,class (:background ,neptune-purple-1))))
       `(compilation-error ((,class (:foreground ,neptune-red-0))))
       `(compilation-info ((,class (:foreground ,neptune-yellow))))
       `(compilation-line-number ((,class (:foreground ,neptune-grey-0))))
       `(compilation-mode-line-exit ((,class (:foreground ,neptune-green-0))))
       `(compilation-mode-line-fail ((,class (:foreground ,neptune-red-0))))
       `(compilation-mode-line-run ((,class (:foreground ,neptune-yellow))))
       `(ediff-odd-diff-A ((,class (:foreground ,neptune-red-0 :background ,neptune-grey-2))))
       `(ediff-odd-diff-B ((,class (:foreground ,neptune-green-0 :background ,neptune-grey-2))))
       `(emmet-preview-output ((,class (:background ,neptune-purple-1))))
       `(elixir-atom-face ((,class (:foreground ,neptune-blue))))
       `(elixir-attribute-face ((,class (:foreground ,neptune-red-0))))
       `(erc-notice-face ((,class (:foreground ,neptune-yellow))))
       `(erc-prompt-face ((,class (:foreground ,neptune-fg))))
       `(erc-timestamp-face ((,class (:foreground ,neptune-purple))))
       `(eshell-prompt ((,class (:foreground ,neptune-red-0))))
       `(eshell-ls-directory ((,class (:weight normal :foreground ,neptune-green-2))))
       `(eshell-ls-executable ((,class (:weight normal :foreground ,neptune-red-0))))
       `(eshell-ls-product ((,class (:foreground ,neptune-fg))))
       `(eshell-ls-symlink ((,class (:weight normal :foreground ,neptune-purple))))
       `(git-commit-comment-file ((,class (:foreground ,neptune-fg))))
       `(git-commit-comment-heading ((,class (:foreground ,neptune-yellow))))
       `(git-commit-summary ((,class (:foreground ,neptune-fg))))
       `(iedit-occurrence ((,class (:foreground ,neptune-red-1))))
       `(isearch ((,class (:foreground ,neptune-fg :background ,neptune-red-1))))
       `(isearch-fail ((,class (:background ,neptune-red-1))))
       `(ido-first-match ((,class (:foreground ,neptune-yellow))))
       `(ido-only-match ((,class (:foreground ,neptune-green-0))))
       `(ido-subdir ((,class (:foreground ,neptune-fg))))
       `(ido-virtual ((,class (:foreground ,neptune-purple))))
       `(ivy-current-match ((,class (:background ,neptune-purple))))
       `(ivy-minibuffer-match-face-1 ((,class (:foreground ,neptune-orange))))
       `(ivy-minibuffer-match-face-2 ((,class (:foreground ,neptune-orange))))
       `(ivy-minibuffer-match-face-3 ((,class (:foreground ,neptune-orange))))
       `(ivy-minibuffer-match-face-4 ((,class (:foreground ,neptune-orange))))
       `(lazy-highlight ((,class (:foreground ,neptune-red-1 :background nil))))
       `(linum ((,class (:slant italic :foreground ,neptune-grey-4))))


       `(diff-added          ((t (:foreground ,neptune-green-0))))
       `(diff-changed        ((t (:foreground ,neptune-yellow))))
       `(diff-removed        ((t (:foreground ,neptune-red-2))))
       `(diff-refine-added   ((t (:foreground ,neptune-green-0))))
       `(diff-refine-change  ((t (:foreground ,neptune-yellow))))
       `(diff-refine-removed ((t (:foreground ,neptune-red-0))))

       `(magit-blame-heading ((,class (:foreground ,neptune-grey-1 :background ,neptune-grey-2))))
       `(magit-branch-local ((,class (:foreground ,neptune-green-2))))
       `(magit-branch-remote ((,class (:foreground ,neptune-green-2))))
       `(magit-section-heading ((,class (:foreground ,neptune-yellow :background ,neptune-grey-2))))
       `(magit-diff-added ((,class (:foreground ,neptune-green-0))))
       `(magit-diff-added-highlight ((,class (:foreground ,neptune-green-0 :inherit (magit-section-highlight)))))
       `(magit-diff-context ((,class (:foreground ,neptune-fg))))
       `(magit-diff-context-highlight ((,class (:foreground ,neptune-fg :inherit (magit-section-highlight)))))
       `(magit-diff-file-heading ((,class (:weight normal :foreground ,neptune-fg :background ,neptune-bg))))
       `(magit-diff-file-heading-highlight ((,class (:weight normal :foreground ,neptune-fg :background ,neptune-grey-2))))
       `(magit-diff-hunk-heading ((,class (:foreground ,neptune-yellow :background ,neptune-grey-2))))
       `(magit-diff-hunk-heading-highlight ((,class (:foreground ,neptune-yellow :background ,neptune-grey-3))))
       `(magit-diff-lines-heading ((,class (:foreground ,neptune-fg :background ,neptune-purple))))
       `(magit-diff-removed ((,class (:foreground ,neptune-red-0))))
       `(magit-diff-removed-highlight ((,class (:foreground ,neptune-red-0 :inherit (magit-section-highlight)))))
       `(magit-diffstat-added ((,class (:foreground ,neptune-green-0))))
       `(magit-diffstat-removed ((,class (:foreground ,neptune-red-0))))
       `(magit-hash ((,class (:foreground ,neptune-red-1))))
       `(magit-section-highlight ((,class (:background ,neptune-grey-2))))

       `(match ((,class (:background ,neptune-red-1))))
       `(minibuffer-prompt ((,class (:foreground ,neptune-fg))))
       `(mmm-default-submode-face ((,class (:background ,neptune-bg))))

       `(mode-line ((,class (:foreground ,neptune-fg :background ,neptune-red-0))))
       `(mode-line-inactive ((,class (:foreground ,neptune-grey-4 :background ,neptune-red-0))))

       `(org-checkbox ((,class (:foreground ,neptune-green-0))))
       `(org-date ((,class (:foreground ,neptune-grey-0))))
       `(org-done ((,class (:foreground ,neptune-green-2))))
       `(org-level-1 ((,class (:foreground ,neptune-red-2))))
       `(org-level-2 ((,class (:foreground ,neptune-yellow))))
       `(org-level-3 ((,class (:foreground ,neptune-green-0))))
       `(org-level-4 ((,class (:foreground ,neptune-orange))))
       `(org-level-5 ((,class (:foreground ,neptune-purple))))
       `(org-level-6 ((,class (:foreground ,neptune-red-0))))
       `(org-level-7 ((,class (:foreground ,neptune-blue))))
       `(org-level-8 ((,class (:foreground ,neptune-green-0))))
       `(org-link ((,class (:foreground ,neptune-blue))))
       `(org-special-keyword ((,class (:foreground ,neptune-purple))))
       `(org-todo ((,class (:foreground ,neptune-red-3))))
       `(region ((,class (:background ,neptune-purple-1))))
       `(shm-current-face ((,class (:background ,neptune-grey-4))))
       `(shm-quarantine-face ((,class (:background ,neptune-red-1))))
       `(smerge-markers ((,class (:foreground ,neptune-yellow :background ,neptune-grey-2))))
       `(smerge-mine ((,class (:foreground ,neptune-fg :background ,neptune-purple))))
       `(smerge-other ((,class (:foreground ,neptune-fg :background ,neptune-green-0))))
       `(smerge-refined-change ((,class (:foreground ,neptune-green-0))))
       `(sp-pair-overlay-face ((,class (:background ,neptune-grey-4))))
       `(sp-show-pair-match-face ((,class (:background ,neptune-grey-5))))
       `(swiper-match-face-1 ((,class (:foreground ,neptune-red-1))))
       `(swiper-match-face-2 ((,class (:foreground ,neptune-red-1))))
       `(swiper-match-face-3 ((,class (:foreground ,neptune-red-1))))
       `(swiper-match-face-4 ((,class (:foreground ,neptune-red-1))))
       `(trailing-whitespace ((,class (:background ,neptune-red-1))))

       ;;----------------------------------------------------------------------------
       ;; Web mode
       ;;----------------------------------------------------------------------------

       `(web-mode-builtin-face ((,class (:foreground ,neptune-blue))))
       `(web-mode-html-attr-name-face ((,class (:foreground ,neptune-orange))))
       `(web-mode-html-tag-face ((,class (:foreground ,neptune-blue))))
       `(web-mode-html-tag-bracket-face ((,class (:foreground ,neptune-blue))))
       `(web-mode-symbol-face ((,class (:foreground ,neptune-green-0))))
       `(which-key-group-description-face ((,class (:foreground ,neptune-grey-0))))
       `(which-key-key-face ((,class (:foreground ,neptune-green-0))))
       `(whitespace-trailing ((,class (:background ,neptune-red-1))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'neptune)

;;; neptune-theme.el ends here
