;; Blackboard Theme for Emacs.
;;
;; Defines a colour scheme resembling that of the original Textmate Blackboard theme.
;; To use add the following to your .emacs file (requires the color-theme package):
;;
;; (require 'color-theme)
;; (color-theme-initialize)
;; (load-file "~/.emacs.d/color-theme/color-theme-twilight.el")
;;
;; And then (color-theme-twilight) to activate it.
;;
;; Several areas still require improvement such as recognition of code that ruby-mode doesn't
;; yet pick up (eg. parent classes), Rails/Merb keywords, or non Ruby code related areas
;; (eg. dired, HTML, etc). Please feel free to customize further and send in any improvements,
;; patches most welcome.
;;
;; MIT License Copyright (c) 2008 Matt Sears <matt@mattsears.com>
;; Credits due to the excellent TextMate Blackboard theme
;;
(defun color-theme-twilight()
  "Emacs color theme by Matt Sears, based off the TextMate Blackboard theme, created 2008-08-18"
  (interactive)
  (color-theme-install
   '(color-theme-twilight
     ((background-color . "#0C1021")
      (background-mode . dark)
      (border-color . "#dedede")
      (cursor-color . "#AFAFAF")
      (foreground-color . "#F8F8F8")
      (mouse-color . "sienna1"))
     ((help-highlight-face . underline)
      (list-matching-lines-face . bold)
      (sgml-set-face . "#7587A6")
      (tags-tag-face . "#7587A6"))
     (twilight-black ((t (:foreground "#0C1021"))))
     (twilight-white ((t (:foreground "#F8F8F8"))))
     (twilight-blue ((t (:foreground "#8798b3"))))
     (twilight-light-blue ((t (:foreground "#e5e5e5"))))
     (twilight-yellow ((t (:foreground "#CF6A4C"))))
     (twilight-brown ((t (:foreground "#CDA869"))))
     (twilight-purple ((t (:foreground "#aa97ab"))))
     (twilight-orange ((t (:foreground "#9B703F"))))
     (twilight-green ((t (:foreground "#9fab7d"))))
     (twilight-light-green ((t (:foreground "#e3f3b2"))))
     (twilight-red ((t (:foreground "#CF6A4C"))))
     (twilight-grey ((t (:foreground "#726d73"))))
     (twilight-bg ((t (:background "#0C1021"))))
     (twilight-highlight ((t (:background "#344e87"))))
     (twilight-current-line ((t (:background "#22283c"))))

     (text-face ((t (:foreground twilight-yellow))))

     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (border-glyph ((t (nil))))
     (border ((t (:inherit twilight-bg))))
     (buffers-tab ((t (:inherit twilight-blue))))

     (font-lock-builtin-face ((t (:inherit twilight-orange))))
     (font-lock-comment-face ((t (:inherit twilight-grey))))
     (font-lock-comment-delimiter-face ((t (:inherit twilight-grey))))
     (font-lock-constant-face ((t (:inherit twilight-red))))
     (font-lock-doc-string-face ((t (:inherit twilight-green))))
     (font-lock-doc-face ((t (:inherit twilight-light-green))))
     (font-lock-function-name-face ((t (:inherit twilight-orange))))
     (font-lock-keyword-face ((t (:inherit twilight-brown))))
     (font-lock-preprocessor-face ((t (:inherit twilight-blue))))

     (font-lock-reference-face ((t (:inherit twilight-blue))))
     (font-lock-regexp-grouping-backslash ((t (:inherit twilight-orange))))
     (font-lock-regexp-grouping-construct ((t (:inherit twilight-red))))
     (font-lock-string-face ((t (:inherit twilight-green))))
     (font-lock-type-face ((t (:inherit twilight-orange))))
     (font-lock-variable-name-face ((t (:inherit twilight-blue))))
     (font-lock-warning-face ((t (:inherit twilight-red))))
     (font-lock-negation-char-face ((t (nil))))
     (header-line ((t (:bold t :weight bold :underline t :foreground "grey20" :box nil))))

     (dired-face-directory ((t (:inherit twilight-blue))))
     (dired-face-executable ((t (:inherit twilight-green))))
     (dired-face-flagged ((t (:inherit twilight-yellow))))
     (dired-face-marked ((t (:inherit twilight-yellow))))
     (dired-face-permissions ((t (:inherit twilight-blue))))
     (dired-face-boring ((t (:inherit twilight-grey))))
     (dired-face-header ((t (:inherit twilight-blue))))
     (dired-face-setuid ((t (:inherit twilight-red))))
     (dired-face-socket ((t (:inherit twilight-red))))
     (dired-face-symlink ((t (:inherit twilight-green))))

     (eshell-prompt-face ((t (:inherit twilight-green))))
     (eshell-prompt ((t (:inherit twilight-green))))
     (eshell-ls-archive-face ((t (:inherit twilight-blue))))
     (eshell-ls-archive ((t (:inherit twilight-blue))))
     (eshell-ls-backup-face ((t (:inherit twilight-orange))))
     (eshell-ls-backup ((t (:inherit twilight-orange))))
     (eshell-ls-clutter-face ((t (:inherit twilight-white))))
     (eshell-ls-clutter ((t (:inherit twilight-white))))
     (eshell-ls-directory-face ((t (:inherit twilight-blue))))
     (eshell-ls-directory ((t (:inherit twilight-blue))))
     (eshell-ls-executable-face ((t (:inherit twilight-white))))
     (eshell-ls-executable ((t (:inherit twilight-white))))
     (eshell-ls-missing-face ((t (:inherit twilight-green))))
     (eshell-ls-missing ((t (:inherit twilight-white))))
     (eshell-ls-product-face ((t (:inherit twilight-green))))
     (eshell-ls-product ((t (:inherit twilight-green))))
     (eshell-ls-readonly-face ((t (:inherit twilight-red))))
     (eshell-ls-readonly ((t (:inherit twilight-red))))
     (eshell-ls-special-face ((t (:inherit twilight-yellow))))
     (eshell-ls-special ((t (:inherit twilight-yellow))))
     (eshell-ls-symlink-face ((t (:inherit twilight-blue))))
     (eshell-ls-symlink ((t (:inherit twilight-blue))))
     (eshell-ls-unreadable-face ((t (:inherit twilight-red))))
     (eshell-ls-unreadable ((t (:inherit twilight-red))))

     (flyspell-duplicate-face ((t (:underline t))))
     (flyspell-incorrect-face ((t (:box (:line-width 1 :color "#b9402a")))))
     (fringe ((t (:inherit twilight-bg))))

     (isearch ((t (:inherit twilight-highlight))))
     (isearch-lazy-highlight-face ((t (:inherit twilight-highlight))))
     (isearch-secondary ((t (:inherit twilight-highlight))))
     (isearch-fail ((t (:inherit twilight-red))))

     ;; ibuffer
     (ibuffer-deletion-face ((t (twilight-red))))
     (ibuffer-filter-group-name-face ((t (twilight-blue))))
     (ibuffer-marked-face ((t (twilight-grey))))
     (ibuffer-title-face ((t (twilight-green))))
     (ibuffer-dired-buffer-face ((t (twilight-blue))))
     (ibuffer-help-buffer-face ((t (twilight-blue))))
     (ibuffer-hidden-buffer-face ((t (twilight-red))))
     (ibuffer-occur-match-face ((t (twilight-red))))
     (ibuffer-read-only-buffer-face ((t (twilight-red))))
     (ibuffer-special-buffer-face ((t (twilight-red))))
     (ibuffer-title-face ((t (twilight-blue))))

     ;; ido
     (ido-first-match ((t (:inherit twilight-green))))
     (ido-first-match-face ((t (:inherit twilight-yellow))))
     (ido-incomplete-regexp ((t (:box (:line-width 1 :color "red4") :foreground "red2"))))
     (ido-indicator ((t (:inherit twilight-yellow))))
     (ido-indicator-face ((t (:inherit twilight-red))))
     (ido-only-match ((t (:inherit twilight-green))))
     (ido-only-match-face ((t (:inherit twilight-green))))
     (ido-subdir ((t (:inherit twilight-yellow))))
     (ido-subdir-face ((t (:inherit twilight-blue))))

     ;; nxml
     (nxml-name-face ((t (:inherit twilight-blue))))
     (nxml-comment-content-face ((t (:inherit twilight-grey))))
     (nxml-markup-declaration-delimiter-face ((t (:inherit twilight-grey))))
     (nxml-name ((t (:inherit twilight-blue))))
     (nxml-ref ((t (:inherit twilight-blue))))
     (nxml-ref-face ((t (:inherit twilight-blue))))
     (nxml-delimiter ((t (:inherit twilight-blue))))
     (nxml-delimiter-face ((t (:inherit twilight-blue))))
     (nxml-text ((t (:inherit twilight-blue))))
     (nxml-text-face ((t (nil))))
     (nxml-delimited-data ((t (:inherit font-lock-string))))
     (nxml-delimited-data-face ((t (:inherit twilight-blue))))
     (nxml-tag-delimiter-face ((t (:inherit twilight-blue))))
     (nxml-attribute-value ((t (:inherit twilight-green))))
     (nxml-attribute-value-face ((t (:inherit twilight-green))))
     (nxml-attribute-value-delimiter ((t (:inherit twilight-green))))
     (nxml-attribute-prefix ((t (:inherit twilight-blue))))
     (nxml-attribute-prefix-face ((t (:inherit twilight-green))))
     (nxml-attribute-local-name ((t (:inherit twilight-green))))
     (nxml-comment-content ((t (:inherit twilight-grey))))
     (nxml-comment-delimiter ((t (:inherit twilight-grey))))
     (nxml-comment-delimiter-face ((t (:inherit twilight-grey))))
     (nxml-processing-instruction-target ((t (:inherit twilight-blue))))
     (nxml-processing-instruction-delimiter ((t (:inherit nxml-processing-instruction-target))))
     (nxml-processing-instruction-content ((t (:inherit nxml-processing-instruction-target))))
     (nxml-cdata-section-CDATA ((t (:inherit twilight-grey))))
     (nxml-cdata-section-delimiter ((t (:inherit nxml-cdata-section-CDATA))))
     (nxml-cdata-section-content ((t (:inherit nxml-text))))
     (nxml-entity-ref-name((t (:inherit twilight-blue))))
     (nxml-entity-ref-delimiter ((t (:inherit nxml-entity-ref-name))))
     (nxml-char-ref-number ((t (:inherit nxml-entity-ref-name))))
     (nxml-char-ref-delimiter ((t (:inherit nxml-entity-ref-delimiter))))
     (nxml-tag-delimiter ((t (:inherit twilight-blue))))
     (nxml-tag-slash ((t (:inherit twilight-blue))))
     (nxml-element-local-name ((t (:inherit twilight-blue))))
     (nxml-element-prefix ((t (:inherit twilight-blue))))
     (nxml-element-colon ((t (:inherit twilight-blue))))
     (nxml-namespace-attribute-prefix ((t (:inherit twilight-blue))))
     (nxml-namespace-attribute-xmlns ((t (:inherit nxml-attribute-prefix))))
     (nxml-attribute-colon ((t (:inherit twilight-blue))))
     (nxml-namespace-attribute-colon ((t (:inherit nxml-attribute-colon))))
     (nxml-hash-face ((t (:inherit twilight-yellow))))

     (mmm-code-submode-face ((t (:inherit twilight-white ))))
     (mmm-comment-submode-face ((t (:inherit twilight-grey))))
     (mmm-default-submode-face ((t (nil))))
     (mmm-output-submode-face ((t (:inherit twilight-white ))))
     (mmm-declaration-submode-face ((t (:inherit twilight-yellow))))

     ;; ERB (Ruby Embedded in HTML)
     (erb-face ((t (:inherit twilight-white))))
     (erb-delim-face ((t (:inherit twilight-white))))
     (erb-out-face ((t (:inherit twilight-white))))
     (erb-out-delim-face ((t (:inherit twilight-white))))
     (erb-comment-delim-face ((t (:inherit twilight-grey))))
     (erb-comment-face ((t (:italic t :inherit twilight-grey))))


     ;; Do not highlight snippets
     (yas/field-highlight-face ((t (nil))))

     ;; org mode
     (org-level-1 ((t (:inherit twilight-blue))))
     (org-level-2 ((t (:inherit twilight-orange))))
     (org-level-3 ((t (:inherit twilight-green))))
     (org-level-4 ((t (:inherit twilight-blue))))
     (org-special-keyword ((t (:inherit twilight-blue))))
     (org-property-value ((t (:inherit twilight-green))))
     (org-link ((t (:inherit twilight-green :underline t))))
     (org-target ((t (:inherit twilight-white))))
     (org-date ((t (:inherit twilight-red))))
     (org-sexp-date ((t (:inherit twilight-red))))
     (org-tag ((t (:inherit twilight-green))))
     (org-todo ((t (:inherit twilight-green))))
     (org-done ((t (:inherit twilight-orange))))
     (org-headline-done ((t (:inherit twilight-green))))

     ;; ERC
     (erc-default-face ((t (:inherit twilight-blue))))
     (erc-fool-face ((t (:inherit twilight-red))))
     (erc-input-face ((t (:inherit twilight-white))))
     (erc-keyword-face ((t (:inherit twilight-orange))))
     (erc-timestamp-face ((t (:inherit twilight-orange))))
     (erc-notice-face ((t (:inherit twilight-green))))
     (erc-prompt-face ((t (:inherit twilight-white))))

     ;; Anything.el
     (anything-header ((t (:inherit twilight-blue))))
     (anything-isearch-match ((t (:inherit twilight-red))))

     (mode-line ((t (:background "#373c4e" :foreground "#afafaf" ))))
     (mode-line-inactive ((t (:foreground "#d2e0f6" :background "#373c4e"))))
     (modeline-buffer-id ((t (:bold t))))

     (lazy-highlight-face ((t (:inherit twilight-current-line))))
     (hl-line ((t (:inherit twilight-current-line))))
     (highlight ((t (:inherit twilight-current-line))))
     (highline-face ((t (:inherit twilight))))
     (minibuffer-prompt ((t (:inherit twilight-blue))))

     (region ((t (:inherit twilight-highlight))))

     (show-paren-match-face ((t (nil))))
     (show-paren-match-face ((t (:inherit twilight-orange))))
     (show-paren-mismatch-face ((t (:inherit twilight-red))))

     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (underline ((nil (:underline nil))))
     (vertical-border ((t (nil))))
     (semantic-dirty-token-face ((t (:inherit twilight-bg))))
     (semantic-unmatched-syntax-face ((t (nil))))
     (zmacs-region ((t (:inherit twilight-blue)))))))
