;; Blackboard Theme for Emacs.
;;
;; Defines a colour scheme resembling that of the original Textmate Blackboard theme.
;; To use add the following to your .emacs file (requires the color-theme package):
;;
;; (require 'color-theme)
;; (color-theme-initialize)
;; (load-file "~/.emacs.d/color-theme/color-theme-blackboard.el")
;;
;; And then (color-theme-blackboard) to activate it.
;;
;; Several areas still require improvement such as recognition of code that ruby-mode doesn't
;; yet pick up (eg. parent classes), Rails/Merb keywords, or non Ruby code related areas
;; (eg. dired, HTML, etc). Please feel free to customize further and send in any improvements,
;; patches most welcome.
;;
;; MIT License Copyright (c) 2008 Matt Sears <matt@mattsears.com>
;; Credits due to the excellent TextMate Blackboard theme
;;
(defun color-theme-blackboard ()
  "Emacs color theme by Matt Sears, based off the TextMate Blackboard theme, created 2008-08-18"
  (interactive)
  (color-theme-install
   '(color-theme-blackboard
     ((background-color . "#0C1021")
      (background-mode . dark)
      (border-color . "#dedede")
      (cursor-color . "#AFAFAF")
      (foreground-color . "#F8F8F8")
      (mouse-color . "sienna1"))
     (blackboard-black ((t (:foreground "#0C1021"))))
     (blackboard-white ((t (:foreground "#F8F8F8"))))
     (blackboard-blue ((t (:foreground "#7587A6"))))
     (blackboard-yellow ((t (:foreground "#fce241"))))
     (blackboard-orange ((t (:foreground "#FF6400"))))
     (blackboard-green ((t (:foreground "#61CE3C"))))
     (blackboard-red ((t (:foreground "#b9402a"))))
     (blackboard-grey ((t (:foreground "#AFAFAF"))))
     (blackboard-bg ((t (:background "#0C1021"))))
     (blackboard-highlight ((t (:background "#344e87"))))
     (blackboard-current-line ((t (:background "#22283c"))))

     (text-face ((t (:foreground blackboard-yellow))))

     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (border-glyph ((t (nil))))
     (border ((t (:inherit blackboard-bg))))
     (buffers-tab ((t (:inherit blackboard-blue))))

     (dired-face-directory ((t (:inherit blackboard-yellow))))
     (dired-face-executable ((t (:inherit blackboard-green))))
     (dired-face-flagged ((t (:inherit blackboard-yellow))))
     (dired-face-marked ((t (:inherit blackboard-yellow))))
     (dired-face-permissions ((t (:inherit blackboard-blue))))
     (dired-face-boring ((t (:inherit blackboard-gray))))
     (dired-face-header ((t (:inherit blackboard-blue))))
     (dired-face-setuid ((t (:inherit blackboard-red))))
     (dired-face-socket ((t (:inherit blackboard-red))))
     (dired-face-symlink ((t (:inherit blackboard-green))))

     (eshell-prompt-face ((t (:inherit blackboard-green))))
     (eshell-prompt ((t (:inherit blackboard-green))))
     (eshell-ls-archive-face ((t (:inherit blackboard-blue))))
     (eshell-ls-archive ((t (:inherit blackboard-blue))))
     (eshell-ls-backup-face ((t (:inherit blackboard-orange))))
     (eshell-ls-backup ((t (:inherit blackboard-orange))))
     (eshell-ls-clutter-face ((t (:inherit blackboard-white))))
     (eshell-ls-clutter ((t (:inherit blackboard-white))))
     (eshell-ls-directory-face ((t (:inherit blackboard-blue))))
     (eshell-ls-directory ((t (:inherit blackboard-blue))))
     (eshell-ls-executable-face ((t (:inherit blackboard-white))))
     (eshell-ls-executable ((t (:inherit blackboard-white))))
     (eshell-ls-missing-face ((t (:inherit blackboard-green))))
     (eshell-ls-missing ((t (:inherit blackboard-white))))
     (eshell-ls-product-face ((t (:inherit blackboard-green))))
     (eshell-ls-product ((t (:inherit blackboard-green))))
     (eshell-ls-readonly-face ((t (:inherit blackboard-red))))
     (eshell-ls-readonly ((t (:inherit blackboard-red))))
     (eshell-ls-special-face ((t (:inherit blackboard-yellow))))
     (eshell-ls-special ((t (:inherit blackboard-yellow))))
     (eshell-ls-symlink-face ((t (:inherit blackboard-blue))))
     (eshell-ls-symlink ((t (:inherit blackboard-blue))))
     (eshell-ls-unreadable-face ((t (:inherit blackboard-red))))
     (eshell-ls-unreadable ((t (:inherit blackboard-red))))

     (flyspell-duplicate-face ((t (:underline t))))
     (flyspell-incorrect-face ((t (:box (:line-width 1 :color "#b9402a")))))
     (fringe ((t (:inherit blackboard-bg))))

     (font-lock-builtin-face ((t (:inherit blackboard-orange))))
     (font-lock-comment-face ((t (:inherit blackboard-grey))))
     (font-lock-comment-delimiter-face ((t (:inherit blackboard-grey))))
     (font-lock-constant-face ((t (:inherit blackboard-yellow))))
     (font-lock-doc-string-face ((t (:inherit blackboard-green))))
     (font-lock-doc-face ((t (:inherit blackboard-green))))
     (font-lock-function-name-face ((t (:inherit blackboard-orange))))
     (font-lock-keyword-face ((t (:inherit blackboard-yellow))))
     (font-lock-preprocessor-face ((t (:inherit blackboard-blue))))
     (font-lock-reference-face ((t (:inherit blackboard-blue))))
     (font-lock-regexp-grouping-backslash ((t (:inherit blackboard-orange))))
     (font-lock-regexp-grouping-construct ((t (:inherit blackboard-red))))
     (font-lock-string-face ((t (:inherit blackboard-green))))
     (font-lock-type-face ((t (:inherit blackboard-orange))))
     (font-lock-variable-name-face ((t (:inherit blackboard-blue))))
     (font-lock-warning-face ((t (:inherit blackboard-red))))
     (font-lock-negation-char-face ((t (nil))))
     (header-line ((t (:bold t :weight bold :underline t :foreground "grey20" :box nil))))

     (isearch ((t (:inherit blackboard-highlight))))
     (isearch-lazy-highlight-face ((t (:inherit blackboard-highlight))))
     (isearch-secondary ((t (:inherit blackboard-highlight))))
     (isearch-fail ((t (:inherit blackboard-red))))

     ;; ibuffer
     (ibuffer-deletion-face ((t (blackboard-red))))
     (ibuffer-filter-group-name-face ((t (blackboard-blue))))
     (ibuffer-marked-face ((t (blackboard-grey))))
     (ibuffer-title-face ((t (blackboard-green))))
     (ibuffer-dired-buffer-face ((t (blackboard-blue))))
     (ibuffer-help-buffer-face ((t (blackboard-blue))))
     (ibuffer-hidden-buffer-face ((t (blackboard-red))))
     (ibuffer-occur-match-face ((t (blackboard-red))))
     (ibuffer-read-only-buffer-face ((t (blackboard-red))))
     (ibuffer-special-buffer-face ((t (blackboard-red))))
     (ibuffer-title-face ((t (blackboard-blue))))

     ;; ido
     (ido-first-match ((t (:inherit blackboard-green))))
     (ido-first-match-face ((t (:inherit blackboard-yellow))))
     (ido-incomplete-regexp ((t (:box (:line-width 1 :color "red4") :foreground "red2"))))
     (ido-indicator ((t (:inherit blackboard-yellow))))
     (ido-indicator-face ((t (:inherit blackboard-red))))
     (ido-only-match ((t (:inherit blackboard-green))))
     (ido-only-match-face ((t (:inherit blackboard-green))))
     (ido-subdir ((t (:inherit blackboard-yellow))))
     (ido-subdir-face ((t (:inherit blackboard-blue))))

     (nxml-name-face ((t (:inherit blackboard-blue))))
     (nxml-comment-content-face ((t (:inherit blackboard-grey))))
     (nxml-markup-declaration-delimiter-face ((t (:inherit blackboard-grey))))
     (nxml-name ((t (:inherit blackboard-blue))))
     (nxml-ref ((t (:inherit blackboard-blue))))
     (nxml-ref-face ((t (:inherit blackboard-blue))))
     (nxml-delimiter ((t (:inherit blackboard-blue))))
     (nxml-delimiter-face ((t (:inherit blackboard-blue))))
     (nxml-text ((t (:inherit blackboard-blue))))
     (nxml-text-face ((t (:inherit blackboard-white))))
     (nxml-delimited-data ((t (:inherit font-lock-string))))
     (nxml-delimited-data-face ((t (:inherit blackboard-blue))))
     (nxml-tag-delimiter-face ((t (:inherit blackboard-blue))))
     (nxml-attribute-value ((t (:inherit blackboard-green))))
     (nxml-attribute-value-face ((t (:inherit blackboard-green))))
     (nxml-attribute-value-delimiter ((t (:inherit blackboard-green))))
     (nxml-attribute-prefix ((t (:inherit blackboard-blue))))
     (nxml-attribute-prefix-face ((t (:inherit blackboard-green))))
     (nxml-attribute-local-name ((t (:inherit blackboard-green))))
     (nxml-comment-content ((t (:inherit blackboard-grey))))
     (nxml-comment-delimiter ((t (:inherit blackboard-grey))))
     (nxml-comment-delimiter-face ((t (:inherit blackboard-grey))))
     (nxml-processing-instruction-target ((t (:inherit blackboard-blue))))
     (nxml-processing-instruction-delimiter ((t (:inherit nxml-processing-instruction-target))))
     (nxml-processing-instruction-content ((t (:inherit nxml-processing-instruction-target))))
     (nxml-cdata-section-CDATA ((t (:inherit blackboard-grey))))
     (nxml-cdata-section-delimiter ((t (:inherit nxml-cdata-section-CDATA))))
     (nxml-cdata-section-content ((t (:inherit nxml-text))))
     (nxml-entity-ref-name((t (:inherit blackboard-blue))))
     (nxml-entity-ref-delimiter ((t (:inherit nxml-entity-ref-name))))
     (nxml-char-ref-number ((t (:inherit nxml-entity-ref-name))))
     (nxml-char-ref-delimiter ((t (:inherit nxml-entity-ref-delimiter))))
     (nxml-tag-delimiter ((t (:inherit blackboard-blue))))
     (nxml-tag-slash ((t (:inherit blackboard-blue))))
     (nxml-element-local-name ((t (:inherit blackboard-blue))))
     (nxml-element-prefix ((t (:inherit blackboard-blue))))
     (nxml-element-colon ((t (:inherit blackboard-blue))))
     (nxml-namespace-attribute-prefix ((t (:inherit blackboard-blue))))
     (nxml-namespace-attribute-xmlns ((t (:inherit nxml-attribute-prefix))))
     (nxml-attribute-colon ((t (:inherit blackboard-blue))))
     (nxml-namespace-attribute-colon ((t (:inherit nxml-attribute-colon))))
     (nxml-hash-face ((t (:inherit blackboard-yellow))))

     (mmm-code-submode-face ((t (nil ))))
     (mmm-comment-submode-face ((t (:inherit blackboard-grey))))
     (mmm-default-submode-face ((t (nil))))
     (mmm-output-submode-face ((t (nil ))))
     (mmm-declaration-submode-face ((t (:inherit blackboard-yellow))))

     ;; Do not highlight snippets
     (yas/field-highlight-face ((t (nil))))

     ;; org mode
     (org-level-1 ((t (:inherit blackboard-blue))))
     (org-level-2 ((t (:inherit blackboard-orange))))
     (org-level-3 ((t (:inherit blackboard-white))))
     (org-level-4 ((t (:inherit blackboard-blue))))
     (org-special-keyword ((t (:inherit blackboard-blue))))
     (org-property-value ((t (:inherit blackboard-green))))
     (org-link ((t (:inherit blackboard-green :underline t))))
     (org-target ((t (:inherit blackboard-white))))
     (org-date ((t (:inherit blackboard-red))))
     (org-sexp-date ((t (:inherit blackboard-red))))
     (org-tag ((t (:inherit blackboard-green))))
     (org-todo ((t (:inherit blackboard-green))))
     (org-done ((t (:inherit blackboard-orange))))
     (org-headline-done ((t (:inherit blackboard-green))))

     (mode-line ((t (:background "#373c4e" :foreground "#afafaf" ))))
     (mode-line-inactive ((t (:foreground "#d2e0f6" :background "#373c4e"))))
     (modeline-buffer-id ((t (:bold t))))

     (lazy-highlight-face ((t (:inherit blackboard-current-line))))
     (hl-line ((t (:inherit blackboard-current-line))))
     (highlight ((t (:inherit blackboard-current-line))))
     (highline-face ((t (:inherit blackboard-current-line))))
     (minibuffer-prompt ((t (:inherit blackboard-blue))))

     (region ((t (:inherit blackboard-highlight))))

     (show-paren-match-face ((t (nil))))
     (show-paren-match-face ((t (:inherit blackboard-orange))))
     (show-paren-mismatch-face ((t (:inherit blackboard-red))))

     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (underline ((nil (:underline nil))))
     (vertical-border ((t (nil))))
     (semantic-dirty-token-face ((t (:inherit blackboard-grey))))
     (semantic-unmatched-syntax-face ((t (nil))))
     (zmacs-region ((t (:inherit blackboard-blue)))))))
